# Generated by Django 2.2 on 2022-04-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industoryname', models.CharField(max_length=125)),
                ('noofmovies', models.IntegerField()),
                ('hitmovies', models.IntegerField()),
                ('screenname', models.CharField(max_length=100)),
            ],
        ),
    ]
