# Generated by Django 2.2 on 2022-03-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyemployee',
            options={'ordering': ['-eno']},
        ),
    ]
